In [19]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.font_manager
from sklearn.model_selection import train_test_split

In [ ]:
#to handle the whitespaces in the columns use sep and encoding as below

In [43]:
data=pd.read_csv('C:\s3\Pattern\proj\diabetes.csv', encoding='utf-8-sig', sep='\s*,\s*', engine='python')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [44]:
df_train, df_test = train_test_split(data,  test_size=0.3)
print (df_train.shape)
print (df_test.shape)

(537, 9)
(231, 9)

In [45]:
df_train.reset_index()

,index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,449,0,120,74,18,63,30.5,0.285,26,0
1,572,3,111,58,31,44,29.5,0.430,22,0
2,190,3,111,62,0,0,22.6,0.142,21,0
3,245,9,184,85,15,0,30.0,1.213,49,1
4,296,2,146,70,38,360,28.0,0.337,29,1
5,443,8,108,70,0,0,30.5,0.955,33,1
6,184,4,141,74,0,0,27.6,0.244,40,0
7,120,0,162,76,56,100,53.2,0.759,25,1
8,122,2,107,74,30,100,33.6,0.404,23,0
9,694,2,90,60,0,0,23.5,0.191,25,0
10,725,4,112,78,40,0,39.4,0.236,38,0
11,693,7,129,68,49,125,38.5,0.439,43,1
12,284,2,108,80,0,0,27.0,0.259,52,1
13,21,8,99,84,0,0,35.4,0.388,50,0
14,586,8,143,66,0,0,34.9,0.129,41,1
15,421,2,94,68,18,76,26.0,0.561,21,0
16,246,10,122,68,0,0,31.2,0.258,41,0
17,581,6,109,60,27,0,25.0,0.206,27,0
18,654,1,106,70,28,135,34.2,0.142,22,0
19,729,2,92,52,0,0,30.1,0.141,22,0
20,269,2,146,0,0,0,27.5,0.240,28,1
21,137,0,93,60,25,92,28.7,0.532,22,0
22,504,3,96,78,39,0,37.3,0.238,40,0
23,580,0,151,90,46,0,42.1,0.371,21,1
24,5,5,116,74,0,0,25.6,0.201,30,0
25,81,2,74,0,0,0,0.0,0.102,22,0
26,722,1,149,68,29,127,29.3,0.349,42,1
27,752,3,108,62,24,0,26.0,0.223,25,0
28,171,6,134,70,23,130,35.4,0.542,29,1
29,10,4,110,92,0,0,37.6,0.191,30,0
...,...,...,...,...,...,...,...,...,...,...
507,609,1,111,62,13,182,24.0,0.138,23,0
508,689,1,144,82,46,180,46.1,0.335,46,1
509,534,1,77,56,30,56,33.3,1.251,24,0
510,316,3,99,80,11,64,19.3,0.284,30,0
511,242,3,139,54,0,0,25.6,0.402,22,1
512,358,12,88,74,40,54,35.3,0.378,48,0
513,483,0,84,82,31,125,38.2,0.233,23,0
514,103,1,81,72,18,40,26.6,0.283,24,0
515,563,6,99,60,19,54,26.9,0.497,32,0
516,356,1,125,50,40,167,33.3,0.962,28,1
517,627,0,132,78,0,0,32.4,0.393,21,0
518,191,9,123,70,44,94,33.1,0.374,40,0
519,154,8,188,78,0,0,47.9,0.137,43,1
520,283,7,161,86,0,0,30.4,0.165,47,1
521,499,6,154,74,32,193,29.3,0.839,39,0
522,203,2,99,70,16,44,20.4,0.235,27,0
523,202,0,108,68,20,0,27.3,0.787,32,0
524,498,7,195,70,33,145,25.1,0.163,55,1
525,608,0,152,82,39,272,41.5,0.270,27,0
526,383,1,90,62,18,59,25.1,1.268,25,0
527,253,0,86,68,32,0,35.8,0.238,25,0
528,346,1,139,46,19,83,28.7,0.654,22,0
529,734,2,105,75,0,0,23.3,0.560,53,0
530,583,8,100,76,0,0,38.7,0.190,42,0
531,381,0,105,68,22,0,20.0,0.236,22,0
532,341,1,95,74,21,73,25.9,0.673,36,0
533,56,7,187,68,39,304,37.7,0.254,41,1
534,615,3,106,72,0,0,25.8,0.207,27,0
535,681,0,162,76,36,0,49.6,0.364,26,1
536,77,5,95,72,33,0,37.7,0.370,27,0

In [69]:
grouped = df_train.groupby('Outcome')


df_mean = grouped.mean()
df_mean

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.394886,110.642045,68.676136,19.701705,67.789773,30.610795,0.434827,31.139205
1,4.870270,139.313514,71.789189,22.832432,99.854054,35.066486,0.512070,37.200000

In [71]:
grouped.std()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.091257,25.604537,18.474367,14.768072,99.880191,7.706500,0.316459,11.174118
1,3.660071,32.120512,20.269218,17.586402,133.684514,7.577495,0.325798,10.582389

In [50]:
for region, df_region in df_train.groupby('Outcome'):
    j = df_region.get_group(key).reset_index(drop=True)
    dictionary['Outcome'] = j.at[0, 'Outcome']
    dictionary['Outcome']

AttributeError: 'DataFrame' object has no attribute 'get_group'